In [24]:
import pandas as pd
import pymongo
import json
from datetime import datetime

In [25]:
df_race_result = pd.read_json("data/race_result.json")
df_pitstop = pd.read_json("data/pit_stop.json")
df_qualif = pd.read_json("data/qualif.json")
df_fastest_a = pd.read_json("data/fastest_a.json")
df_fastest_b = pd.read_json("data/fastest_b.json")
df_fastest = pd.concat([df_fastest_a, df_fastest_b], axis=0)
df_fastest

,title,Date,Position,Number,Driver,Team,Time,Avg_Speed
0,"Jeddah Corniche Circuit, Jeddah",2021-12-05,1,44,Hamilton,Mercedes,1:30.734,244.962
1,"Yas Marina Circuit, Yas Island",2021-12-12,1,33,Verstappen,Red Bull Racing Honda,1:26.103,220.800
2,"Bahrain International Circuit, Sakhir",2021-03-28,1,77,Bottas,Mercedes,1:32.090,211.566
3,"Jeddah Corniche Circuit, Jeddah",2021-12-05,2,77,Bottas,Mercedes,1:31.408,243.155
4,"Jeddah Corniche Circuit, Jeddah",2021-12-05,3,33,Verstappen,Red Bull Racing Honda,1:31.488,242.943
...,...,...,...,...,...,...,...,...
863,"Bahrain International Circuit, Bahrain",2013-04-21,21,19,Ricciardo,STR Ferrari,1:39.579,195.655
864,"Shanghai International Circuit, China",2012-04-15,22,22,de la Rosa,HRT Cosworth,1:43.610,189.398
865,"Shanghai International Circuit, China",2012-04-15,23,23,Karthikeyan,HRT Cosworth,1:43.935,188.806
866,"Bahrain International Circuit, Bahrain",2013-04-21,22,18,Vergne,STR Ferrari,1:43.107,188.960
867,"Shanghai International Circuit, China",2012-04-15,24,7,Schumacher,Mercedes,1:44.109,188.490

In [26]:
df_qualif = df_qualif.rename(columns={'Position':'Pos_Qualif'})
df_qualif

,title,Date,Pos_Qualif,Number,Driver,Team,Q1,Q2,Q3
0,"Bahrain International Circuit, Sakhir",2021-03-28,1,33,Verstappen,Red Bull Racing Honda,1:30.499,1:30.318,1:28.997
1,"Bahrain International Circuit, Sakhir",2021-03-28,2,44,Hamilton,Mercedes,1:30.617,1:30.085,1:29.385
2,"Bahrain International Circuit, Sakhir",2021-03-28,3,77,Bottas,Mercedes,1:31.200,1:30.186,1:29.586
3,"Bahrain International Circuit, Sakhir",2021-03-28,4,16,Leclerc,Ferrari,1:30.691,1:30.010,1:29.678
4,"Bahrain International Circuit, Sakhir",2021-03-28,5,10,Gasly,AlphaTauri Honda,1:30.848,1:30.513,1:29.809
...,...,...,...,...,...,...,...,...,...
4061,"Circuit de Barcelona-Catalunya, Barcelona",2021-05-09,20,9,Mazepin,Haas Ferrari,1:19.807,None,None
4062,"Circuit Paul Ricard, Le Castellet",2021-06-20,NC,18,Stroll,Aston Martin Mercedes,2:12.584,None,None
4063,"Circuit Paul Ricard, Le Castellet",2021-06-20,RT,22,Tsunoda,AlphaTauri Honda,DNF,None,None
4064,"Melbourne Grand Prix Circuit, Australia",2012-03-18,NC,22,de la Rosa,HRT Cosworth,1:33.495,None,None
4065,"Melbourne Grand Prix Circuit, Australia",2012-03-18,NC,23,Karthikeyan,HRT Cosworth,1:33.643,None,None

In [27]:
df_race_result

,title,Date,Position,Number,Driver,Team,Laps,Time,Points
0,"Jeddah Corniche Circuit, Jeddah",2021-12-05,1,44,Hamilton,Mercedes,50.0,2:06:15.118,26.0
1,"AutÃ³dromo JosÃ© Carlos Pace, SÃ£o Paulo",2021-11-14,1,44,Hamilton,Mercedes,71.0,1:32:22.851,25.0
2,"Jeddah Corniche Circuit, Jeddah",2021-12-05,2,33,Verstappen,Red Bull Racing Honda,50.0,+21.825,18.0
3,"Jeddah Corniche Circuit, Jeddah",2021-12-05,3,77,Bottas,Mercedes,50.0,+27.531,15.0
4,"Jeddah Corniche Circuit, Jeddah",2021-12-05,4,31,Ocon,Alpine Renault,50.0,+27.633,12.0
...,...,...,...,...,...,...,...,...,...
4155,"Sepang International Circuit, Malaysia",2012-03-25,21,22,de la Rosa,HRT Cosworth,54.0,+2,0.0
4156,"Circuit de Monaco, Monte Carlo",2021-05-23,NC,16,Leclerc,Ferrari,0.0,DNS,0.0
4157,"Sepang International Circuit, Malaysia",2012-03-25,22,23,Karthikeyan,HRT Cosworth,54.0,+2,0.0
4158,"Sepang International Circuit, Malaysia",2012-03-25,NC,14,Kobayashi,Sauber Ferrari,46.0,DNF,0.0
4159,"Sepang International Circuit, Malaysia",2012-03-25,NC,10,Grosjean,Lotus Renault,3.0,DNF,0.0

In [28]:
df_fastest = df_fastest.rename(columns={'Position':'Speed_Rank','Time':'Lap_Time'})
df_fastest

,title,Date,Speed_Rank,Number,Driver,Team,Lap_Time,Avg_Speed
0,"Jeddah Corniche Circuit, Jeddah",2021-12-05,1,44,Hamilton,Mercedes,1:30.734,244.962
1,"Yas Marina Circuit, Yas Island",2021-12-12,1,33,Verstappen,Red Bull Racing Honda,1:26.103,220.800
2,"Bahrain International Circuit, Sakhir",2021-03-28,1,77,Bottas,Mercedes,1:32.090,211.566
3,"Jeddah Corniche Circuit, Jeddah",2021-12-05,2,77,Bottas,Mercedes,1:31.408,243.155
4,"Jeddah Corniche Circuit, Jeddah",2021-12-05,3,33,Verstappen,Red Bull Racing Honda,1:31.488,242.943
...,...,...,...,...,...,...,...,...
863,"Bahrain International Circuit, Bahrain",2013-04-21,21,19,Ricciardo,STR Ferrari,1:39.579,195.655
864,"Shanghai International Circuit, China",2012-04-15,22,22,de la Rosa,HRT Cosworth,1:43.610,189.398
865,"Shanghai International Circuit, China",2012-04-15,23,23,Karthikeyan,HRT Cosworth,1:43.935,188.806
866,"Bahrain International Circuit, Bahrain",2013-04-21,22,18,Vergne,STR Ferrari,1:43.107,188.960
867,"Shanghai International Circuit, China",2012-04-15,24,7,Schumacher,Mercedes,1:44.109,188.490

In [39]:
df_pitstop = df_pitstop.rename(columns={'Time':'Time_Pit','Laps':'Lap_pit'})
df_pitstop

,title,Date,Num_stop,Number,Driver,Team,Lap_pit,Time_Pit
0,"Circuit of The Americas, Austin",2021-10-24,1,9,Mazepin,Haas Ferrari,1.0,30.673
1,"Intercity Istanbul Park, Istanbul",2021-10-10,1,3,Ricciardo,McLaren Mercedes,21.0,23.028
2,"Sochi Autodrom, Sochi",2021-09-26,1,18,Stroll,Aston Martin Mercedes,12.0,30.241
3,"AutÃ³dromo Hermanos RodrÃ­guez, Mexico City",2021-11-07,1,3,Ricciardo,McLaren Mercedes,1.0,38.128
4,"AutÃ³dromo JosÃ© Carlos Pace, SÃ£o Paulo",2021-11-14,1,4,Norris,McLaren Mercedes,1.0,27.313
...,...,...,...,...,...,...,...,...
8851,"AutÃ³dromo Internacional do Algarve, PortimÃ£o",2021-05-02,4,9,Mazepin,Haas Ferrari,43.0,26.984
8852,"Autodromo Enzo e Dino Ferrari, Imola",2021-04-18,4,99,Giovinazzi,Alfa Romeo Racing Ferrari,40.0,29.742
8853,"AutÃ³dromo Internacional do Algarve, PortimÃ£o",2021-05-02,3,11,Perez,Red Bull Racing Honda,51.0,26.607
8854,"AutÃ³dromo Internacional do Algarve, PortimÃ£o",2021-05-02,4,77,Bottas,Mercedes,63.0,26.573
8855,"AutÃ³dromo Internacional do Algarve, PortimÃ£o",2021-05-02,4,33,Verstappen,Red Bull Racing Honda,64.0,26.319

In [30]:
df1 = pd.merge(df_race_result, df_fastest,  how='right', left_on=['title','Date','Number','Driver','Team'], right_on = ['title','Date','Number','Driver','Team']).fillna("NaN")
df1

,title,Date,Position,Number,Driver,Team,Laps,Time,Points,Speed_Rank,Lap_Time,Avg_Speed
0,"Jeddah Corniche Circuit, Jeddah",2021-12-05,1,44,Hamilton,Mercedes,50.0,2:06:15.118,26.0,1,1:30.734,244.962
1,"Yas Marina Circuit, Yas Island",2021-12-12,1,33,Verstappen,Red Bull Racing Honda,58.0,1:30:17.345,26.0,1,1:26.103,220.800
2,"Bahrain International Circuit, Sakhir",2021-03-28,3,77,Bottas,Mercedes,56.0,+37.383,16.0,1,1:32.090,211.566
3,"Jeddah Corniche Circuit, Jeddah",2021-12-05,3,77,Bottas,Mercedes,50.0,+27.531,15.0,2,1:31.408,243.155
4,"Jeddah Corniche Circuit, Jeddah",2021-12-05,2,33,Verstappen,Red Bull Racing Honda,50.0,+21.825,18.0,3,1:31.488,242.943
...,...,...,...,...,...,...,...,...,...,...,...,...
3974,"Bahrain International Circuit, Bahrain",2013-04-21,16,19,Ricciardo,STR Ferrari,56.0,+1,0.0,21,1:39.579,195.655
3975,"Shanghai International Circuit, China",2012-04-15,21,22,de la Rosa,HRT Cosworth,55.0,+1,0.0,22,1:43.610,189.398
3976,"Shanghai International Circuit, China",2012-04-15,22,23,Karthikeyan,HRT Cosworth,54.0,+2,0.0,23,1:43.935,188.806
3977,"Bahrain International Circuit, Bahrain",2013-04-21,NC,18,Vergne,STR Ferrari,16.0,DNF,0.0,22,1:43.107,188.960
3978,"Shanghai International Circuit, China",2012-04-15,NC,7,Schumacher,Mercedes,12.0,DNF,0.0,24,1:44.109,188.490

In [54]:
df2 = pd.merge(df1, df_pitstop,  how='right', left_on=['title','Date','Number','Driver','Team'], right_on = ['title','Date','Number','Driver','Team']).fillna('NaN')
df2.shape

(8856, 15)

In [32]:
df_race = pd.merge(df1, df_qualif,  how='right', left_on=['title','Date','Number','Driver','Team'], right_on = ['title','Date','Number','Driver','Team']).fillna('NaN')
df_race
#df_race.to_json(r'data/df_race.json')

,title,Date,Position,Number,Driver,Team,Laps,Time,Points,Speed_Rank,Lap_Time,Avg_Speed,Pos_Qualif,Q1,Q2,Q3
0,"Bahrain International Circuit, Sakhir",2021-03-28,2,33,Verstappen,Red Bull Racing Honda,56.0,+0.745,18.0,2.0,1:33.228,208.984,1,1:30.499,1:30.318,1:28.997
1,"Bahrain International Circuit, Sakhir",2021-03-28,1,44,Hamilton,Mercedes,56.0,1:32:03.897,25.0,4.0,1:34.015,207.235,2,1:30.617,1:30.085,1:29.385
2,"Bahrain International Circuit, Sakhir",2021-03-28,3,77,Bottas,Mercedes,56.0,+37.383,16.0,1.0,1:32.090,211.566,3,1:31.200,1:30.186,1:29.586
3,"Bahrain International Circuit, Sakhir",2021-03-28,6,16,Leclerc,Ferrari,56.0,+59.090,8.0,11.0,1:34.988,205.112,4,1:30.691,1:30.010,1:29.678
4,"Bahrain International Circuit, Sakhir",2021-03-28,17,10,Gasly,AlphaTauri Honda,52.0,DNF,0.0,5.0,1:34.090,207.069,5,1:30.848,1:30.513,1:29.809
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4061,"Circuit de Barcelona-Catalunya, Barcelona",2021-05-09,19,9,Mazepin,Haas Ferrari,64.0,+2,0.0,19.0,1:24.040,200.261,20,1:19.807,NaN,NaN
4062,"Circuit Paul Ricard, Le Castellet",2021-06-20,10,18,Stroll,Aston Martin Mercedes,53.0,+91.946,1.0,9.0,1:37.828,214.981,NC,2:12.584,NaN,NaN
4063,"Circuit Paul Ricard, Le Castellet",2021-06-20,13,22,Tsunoda,AlphaTauri Honda,52.0,+1,0.0,19.0,1:38.980,212.479,RT,DNF,NaN,NaN
4064,"Melbourne Grand Prix Circuit, Australia",2012-03-18,NaN,22,de la Rosa,HRT Cosworth,NaN,NaN,NaN,NaN,NaN,NaN,NC,1:33.495,NaN,NaN
4065,"Melbourne Grand Prix Circuit, Australia",2012-03-18,NaN,23,Karthikeyan,HRT Cosworth,NaN,NaN,NaN,NaN,NaN,NaN,NC,1:33.643,NaN,NaN

In [33]:
#df_race = pd.read_json("data/race_result.json")
df_race["Date"] = df_race['Date'].astype(str)
split_date = df_race['Date'].str.split("-",n=1).str[0]
split_date

df_race['title'] = df_race['title'].str.replace("Circuit de Catalunya, Spain","Catalunya, Barcelona")
df_race['title'] = df_race['title'].str.replace("Circuit de Barcelona-Catalunya, Spain","Catalunya, Barcelona")
df_race['title'] = df_race['title'].str.replace("Valencia Street Circuit, Spain","Street Circuit, Valencia")


df_race['Date']


#df[df['Driver']=='RÃ¤ikkÃ¶nen']


#df_race['title'] = df_race[df_race['Date']=="2020-07-12"]['title'].str.replace("Red Bull Ring, Spielberg","Styria, Styria")
#df_race['title'] = df_race[df_race['Date']=="2021-06-27"]['title'].str.replace("Red Bull Ring, Spielberg","Styria, Styria")


df_race.loc[df_race.Date == "2020-07-12", "title"] = "Styria, Styria"
df_race.loc[df_race.Date == "2021-06-27", "title"] = "Styria, Styria"
df_race.loc[df_race.Date == "2020-08-09", "title"] = "Silverstone, Silverstone_70th"



split_gp = df_race['title'].str.split(", ",n=1).str[1]
#type(split_gp)


df_race['Date']=split_date
df_race['title']=split_gp
df_race = df_race.rename(columns={'title':'Grand_Prix','Date':'Year'})

#df_race[(df_race['Year']=="2020") & (df_race['Grand_Prix']=="Silverstone")]

In [155]:
df_race[df_race['Year']=="2014"]

,Grand_Prix,Year,Position,Number,Driver,Team,Laps,Time,Points,Speed_Rank,Lap_Time,Avg_Speed,Pos_Qualif,Q1,Q2,Q3
706,United States,2014,2,6,Rosberg,Mercedes,56.0,+4.314,18.0,5.0,1:41.932,194.706,1,1:38.303,1:36.290,1:36.067
721,Brazil,2014,1,6,Rosberg,Mercedes,71.0,1:30:02.555,25.0,2.0,1:13.619,210.711,1,1:10.347,1:10.303,1:10.023
731,United States,2014,1,44,Hamilton,Mercedes,56.0,1:40:04.785,25.0,4.0,1:41.929,194.712,2,1:37.196,1:37.287,1:36.443
732,United States,2014,5,77,Bottas,Williams Mercedes,56.0,+30.992,10.0,6.0,1:42.505,193.617,3,1:38.249,1:37.499,1:36.906
733,United States,2014,4,19,Massa,Williams Mercedes,56.0,+26.924,12.0,9.0,1:42.971,192.741,4,1:37.877,1:37.347,1:37.205
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3014,Australia,2014,NC,17,Bianchi,Marussia Ferrari,49.0,+8,0.0,15.0,1:35.281,200.363,18,1:34.794,NaN,NaN
3015,Australia,2014,12,21,Gutierrez,Sauber Ferrari,56.0,+1,0.0,12.0,1:34.202,202.658,19,1:35.117,NaN,NaN
3034,Australia,2014,NC,9,Ericsson,Caterham Renault,27.0,DNF,0.0,17.0,1:37.064,196.682,20,1:35.157,NaN,NaN
3035,Australia,2014,NC,8,Grosjean,Lotus Renault,43.0,DNF,0.0,14.0,1:34.766,201.451,21,1:36.993,NaN,NaN
3052,Australia,2014,NC,13,Maldonado,Lotus Renault,29.0,DNF,0.0,18.0,1:37.332,196.141,NC,DNF,NaN,NaN

In [21]:
df_race["Time_Pit"] = df_race['Time_Pit'].astype(str)

df = pd.DataFrame(df_race, columns = ['Year', 'Grand_Prix','Driver','Time_Pit'])
time_pb = df[df_race['Time_Pit'].str.contains(":")]
time_pb

      Year Grand_Prix      Driver   Time_Pit
84    2021   Budapest    Hamilton  24:09.259
121   2021   Budapest  Verstappen  24:16.349
126   2021   Budapest       Gasly  24:17.615
179   2021   Budapest        Ocon  24:10.190
182   2021   Budapest      Alonso  24:14.979
...    ...        ...         ...        ...
7743  2021       Baku  Giovinazzi  33:37.324
7768  2021      Imola  Schumacher  25:21.462
7772  2021      Imola     Mazepin  24:46.154
7775  2021      Imola     Tsunoda  24:51.384
7776  2021      Imola     Tsunoda   1:03.280

[289 rows x 4 columns]

In [34]:
df_race["Avg_Speed"] = df_race['Avg_Speed'].astype("float64")
#df_race['Num_stop'] = df_race['Num_stop'].astype("float64")
df_race['Points'] = df_race['Points'].astype("float64")
df_race['Position'] = pd.to_numeric(df_race['Position'],errors="coerce")
#df_race['Time_Pit'] = pd.to_numeric(df_race['Time_Pit'],errors='coerce')
#df_race['Time_Pit'] = df_race['Time_Pit'].astype("datetime64[ns]",errors="ignore")
df_race['Lap_Time'] = "0" + df_race['Lap_Time'].astype(str)
df_race['Q1'] = "0" + df_race['Q1'].astype(str)
df_race['Q2'] = "0" + df_race['Q2'].astype(str)
df_race['Q3'] = "0" + df_race['Q3'].astype(str)
df_race = df_race.rename(columns={'Time':'Gap_Time'})
#Q1_split = df_race["Q1"].astype(str)
#Q1_split = Q1_split.split()

In [35]:
time_pb = df_race['Lap_Time']
time_pb.dt.microsecond
list_time = pd.DataFrame([time_pb.dt.minute,time_pb.dt.second,time_pb.dt.microsecond])
list_time

,0,1,2,3,4,5,6,7,8,9,...,7818,7819,7820,7821,7822,7823,7824,7825,7826,7827
Lap_Time,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN
Lap_Time,33.0,33.0,34.0,34.0,32.0,32.0,32.0,34.0,34.0,34.0,...,34.0,35.0,35.0,35.0,24.0,24.0,37.0,38.0,NaN,NaN
Lap_Time,228000.0,228000.0,15000.0,15000.0,90000.0,90000.0,90000.0,988000.0,988000.0,90000.0,...,253000.0,11000.0,11000.0,11000.0,40000.0,40000.0,828000.0,980000.0,NaN,NaN

In [35]:
df_race['Grand_Prix'] = df_race['Grand_Prix'].str.replace("Sakhir","Bahrain")
df_race['Grand_Prix'] = df_race['Grand_Prix'].str.replace("Melbourne","Australia")
df_race['Grand_Prix'] = df_race['Grand_Prix'].str.replace("Shanghai","China")
df_race['Grand_Prix'] = df_race['Grand_Prix'].str.replace("Spielberg","Austria")
df_race['Grand_Prix'] = df_race['Grand_Prix'].str.replace("Kuala Lumpur","Malaysia")
df_race['Grand_Prix'] = df_race['Grand_Prix'].str.replace("Budapest","Hungary")
df_race['Grand_Prix'] = df_race['Grand_Prix'].str.replace("Monte Carlo","Monaco")
df_race['Grand_Prix'] = df_race['Grand_Prix'].str.replace("Sochi","Russia")
df_race['Grand_Prix'] = df_race['Grand_Prix'].str.replace("Montreal","Canada")
df_race['Grand_Prix'] = df_race['Grand_Prix'].str.replace("Great Britain","Silverstone")
df_race['Grand_Prix'] = df_race['Grand_Prix'].str.replace("Le Castellet","France")
df_race['Grand_Prix'] = df_race['Grand_Prix'].str.replace("PortimÃ£o","Portugal")
df_race['Grand_Prix'] = df_race['Grand_Prix'].str.replace("Belgium","Spa-Francorchamps")
df_race['Grand_Prix'] = df_race['Grand_Prix'].str.replace("Hockenheim","Germany")
df_race['Grand_Prix'] = df_race['Grand_Prix'].str.replace("NÃ¼rburgring","Germany")
df_race['Grand_Prix'] = df_race['Grand_Prix'].str.replace("Italy","Monza")
df_race['Grand_Prix'] = df_race['Grand_Prix'].str.replace("Mugello","Tuscany")
df_race['Grand_Prix'] = df_race['Grand_Prix'].str.replace("Suzuka","Japan")
df_race['Grand_Prix'] = df_race['Grand_Prix'].str.replace("Istanbul","Turkey")
df_race['Grand_Prix'] = df_race['Grand_Prix'].str.replace("Mexico City","Mexico")
df_race['Grand_Prix'] = df_race['Grand_Prix'].str.replace("Austin","United States")
df_race['Grand_Prix'] = df_race['Grand_Prix'].str.replace("SÃ£o Paulo","Brazil")
df_race['Grand_Prix'] = df_race['Grand_Prix'].str.replace("Lusail","Qatar")
df_race['Lap_Time']

0       01:33.228
1       01:34.015
2       01:32.090
3       01:34.988
4       01:34.090
          ...
4061    01:24.040
4062    01:37.828
4063    01:38.980
4064         0NaN
4065         0NaN
Name: Lap_Time, Length: 4066, dtype: object

In [43]:
df_pitstop["Date"] = df_pitstop['Date'].astype(str)
split_date = df_pitstop['Date'].str.split("-",n=1).str[0]
split_date
split_gp = df_pitstop['title'].str.split(", ",n=1).str[1]
type(split_gp)


df_pitstop['Date']=split_date
df_pitstop['title']=split_gp
df_pitstop = df_pitstop.rename(columns={'title':'Grand_Prix','Date':'Year'})

KeyError: 'Date'

In [58]:
#df_pitstop = pd.read_json("data/pit_stop.json")

df_pitstop['Grand_Prix'] = df_pitstop['Grand_Prix'].str.replace("Sakhir","Bahrain")
df_pitstop['Grand_Prix'] = df_pitstop['Grand_Prix'].str.replace("Melbourne","Australia")
df_pitstop['Grand_Prix'] = df_pitstop['Grand_Prix'].str.replace("Shanghai","China")
df_pitstop['Grand_Prix'] = df_pitstop['Grand_Prix'].str.replace("Spielberg","Austria")
df_pitstop['Grand_Prix'] = df_pitstop['Grand_Prix'].str.replace("Kuala Lumpur","Malaysia")
df_pitstop['Grand_Prix'] = df_pitstop['Grand_Prix'].str.replace("Budapest","Hungary")
df_pitstop['Grand_Prix'] = df_pitstop['Grand_Prix'].str.replace("Monte Carlo","Monaco")
df_pitstop['Grand_Prix'] = df_pitstop['Grand_Prix'].str.replace("Sochi","Russia")
df_pitstop['Grand_Prix'] = df_pitstop['Grand_Prix'].str.replace("Montreal","Canada")
df_pitstop['Grand_Prix'] = df_pitstop['Grand_Prix'].str.replace("Great Britain","Silverstone")
df_pitstop['Grand_Prix'] = df_pitstop['Grand_Prix'].str.replace("Le Castellet","France")
df_pitstop['Grand_Prix'] = df_pitstop['Grand_Prix'].str.replace("PortimÃ£o","Portugal")
df_pitstop['Grand_Prix'] = df_pitstop['Grand_Prix'].str.replace("Belgium","Spa-Francorchamps")
df_pitstop['Grand_Prix'] = df_pitstop['Grand_Prix'].str.replace("Hockenheim","Germany")
df_pitstop['Grand_Prix'] = df_pitstop['Grand_Prix'].str.replace("NÃ¼rburgring","Germany")
df_pitstop['Grand_Prix'] = df_pitstop['Grand_Prix'].str.replace("Italy","Monza")
df_pitstop['Grand_Prix'] = df_pitstop['Grand_Prix'].str.replace("Mugello","Tuscany")
df_pitstop['Grand_Prix'] = df_pitstop['Grand_Prix'].str.replace("Suzuka","Japan")
df_pitstop['Grand_Prix'] = df_pitstop['Grand_Prix'].str.replace("Istanbul","Turkey")
df_pitstop['Grand_Prix'] = df_pitstop['Grand_Prix'].str.replace("Mexico City","Mexico")
df_pitstop['Grand_Prix'] = df_pitstop['Grand_Prix'].str.replace("Austin","United States")
df_pitstop['Grand_Prix'] = df_pitstop['Grand_Prix'].str.replace("SÃ£o Paulo","Brazil")
df_pitstop['Grand_Prix'] = df_pitstop['Grand_Prix'].str.replace("Lusail","Qatar")
df_pitstop



df_pitstop['Num_stop'] = df_pitstop['Num_stop'].astype("float64")


df_pitstop["Time_Pit"] = df_pitstop['Time_Pit'].astype("float64",errors="ignore")

df_pitstop

#time_pb = df_pitstop[~df_pitstop["Time"].str.contains(':')]
#time_pb = "00:" + time_pb
#time_pb['new_time'] = "00:" + time_pb['Time']
#time_pb

,Grand_Prix,Year,Num_stop,Number,Driver,Team,Lap_pit,Time_Pit
0,United States,2021,1.0,9,Mazepin,Haas Ferrari,1.0,30.673
1,Turkey,2021,1.0,3,Ricciardo,McLaren Mercedes,21.0,23.028
2,Russia,2021,1.0,18,Stroll,Aston Martin Mercedes,12.0,30.241
3,Mexico,2021,1.0,3,Ricciardo,McLaren Mercedes,1.0,38.128
4,Brazil,2021,1.0,4,Norris,McLaren Mercedes,1.0,27.313
...,...,...,...,...,...,...,...,...
8851,Portugal,2021,4.0,9,Mazepin,Haas Ferrari,43.0,26.984
8852,Imola,2021,4.0,99,Giovinazzi,Alfa Romeo Racing Ferrari,40.0,29.742
8853,Portugal,2021,3.0,11,Perez,Red Bull Racing Honda,51.0,26.607
8854,Portugal,2021,4.0,77,Bottas,Mercedes,63.0,26.573
8855,Portugal,2021,4.0,33,Verstappen,Red Bull Racing Honda,64.0,26.319

In [13]:
df_fastest_a = pd.read_json("data/fastest_a.json")
df_fastest_b = pd.read_json("data/fastest_b.json")
df_fastest = pd.concat([df_fastest_a, df_fastest_b], axis=0)

df_fastest["Date"] = df_fastest['Date'].astype(str)
split_date = df_fastest['Date'].str.split("-",n=1).str[0]
split_date
split_gp = df_fastest['title'].str.split(", ",n=1).str[1]
type(split_gp)


df_fastest['Date']=split_date
df_fastest['title']=split_gp

df_fastest = df_fastest.rename(columns={'title':'Grand_Prix','Date':'Year'})
df_fastest['Grand_Prix'] = df_fastest['Grand_Prix'].str.replace("Sakhir","Bahrain")
df_fastest

,Grand_Prix,Year,Position,Number,Driver,Team,Time,Avg_Speed
0,Bahrain,2021,1,77,Bottas,Mercedes,1:32.090,211.566
1,Bahrain,2021,2,33,Verstappen,Red Bull Racing Honda,1:33.228,208.984
2,Bahrain,2021,3,11,Perez,Red Bull Racing Honda,1:33.970,207.334
3,Bahrain,2021,4,44,Hamilton,Mercedes,1:34.015,207.235
4,Bahrain,2021,5,10,Gasly,AlphaTauri Honda,1:34.090,207.069
...,...,...,...,...,...,...,...,...
863,Spain,2013,21,21,van der Garde,Caterham Renault,1:30.597,184.973
864,Spain,2013,22,8,Grosjean,Lotus Renault,1:31.136,183.879
865,China,2013,20,2,Webber,Red Bull Racing Renault,1:43.416,189.754
866,China,2013,21,15,Sutil,Force India Mercedes,1:44.257,188.223
867,China,2013,22,12,Gutierrez,Sauber Ferrari,1:44.775,187.292

In [11]:
df_qualif = pd.read_json("data/qualif.json")
df_qualif["Date"] = df_qualif['Date'].astype(str)
split_date = df_qualif['Date'].str.split("-",n=1).str[0]
split_date
split_gp = df_qualif['title'].str.split(", ",n=1).str[1]
type(split_gp)


df_qualif['Date']=split_date
df_qualif['title']=split_gp
df_qualif = df_qualif.rename(columns={'title':'Grand_Prix','Date':'Year'})
df_qualif['Grand_Prix'] = df_qualif['Grand_Prix'].str.replace("Sakhir","Bahrain")

df_qualif

,Grand Prix,Year,Position,Number,Driver,Team,Q1,Q2,Q3
0,Bahrain,2021,1,33,Verstappen,Red Bull Racing Honda,1:30.499,1:30.318,1:28.997
1,Yas Island,2021,1,33,Verstappen,Red Bull Racing Honda,1:23.322,1:22.800,1:22.109
2,Melbourne,2018,1,44,Hamilton,Mercedes,1:22.824,1:22.051,1:21.164
3,Bahrain,2021,2,44,Hamilton,Mercedes,1:30.617,1:30.085,1:29.385
4,Bahrain,2021,3,77,Bottas,Mercedes,1:31.200,1:30.186,1:29.586
...,...,...,...,...,...,...,...,...,...
4513,Imola,2021,RT,22,Tsunoda,AlphaTauri Honda,DNF,None,None
4514,PortimÃ£o,2021,17,18,Stroll,Aston Martin Mercedes,1:19.913,None,None
4515,PortimÃ£o,2021,18,6,Latifi,Williams Mercedes,1:20.285,None,None
4516,PortimÃ£o,2021,19,47,Schumacher,Haas Ferrari,1:20.452,None,None
4517,PortimÃ£o,2021,20,9,Mazepin,Haas Ferrari,1:20.912,None,None

In [16]:
df_tyres = pd.read_json("data/tyres.json")
df_tyres = df_tyres.rename(columns={'title':'Year','GP':'Grand_Prix'})
df_tyres

split_year = df_tyres['Year'].str.split(" ",n=2).str[2]
split_driver = df_tyres['Driver'].str.split(" ",n=1).str[1]


df_tyres['Year']=split_year
df_tyres['Driver']=split_driver
df_tyres[(df_tyres['Grand_Prix']=="Bahrain")&(df_tyres['Year']=="2021")]
#print(df_tyres['Grand_Prix'].unique())
#df_tyres['Grand_Prix']
df_tyres

       Year     Driver Grand_Prix       Tyres  Lap_changed
0      2012     Button  Australia   Soft Used           16
1      2012     Button  Australia  Medium New           36
2      2012     Button  Australia  Medium New           58
3      2012     Vettel  Australia   Soft Used           16
4      2012     Vettel  Australia   Soft Used           37
...     ...        ...        ...         ...          ...
11316  2013     Bottas     Brazil  Medium New           17
11317  2013     Bottas     Brazil    Hard New           41
11318  2013     Bottas     Brazil  Medium New           45
11319  2013   Grosjean     Brazil  Medium New            3
11320  2016  Gutierrez  Abu Dhabi    Soft New           28

[11321 rows x 5 columns]

In [17]:
df_tyres['Grand_Prix'] = df_tyres['Grand_Prix'].str.replace("Sakhir","Bahrain")
df_tyres['Grand_Prix'] = df_tyres['Grand_Prix'].str.replace("Azerbaijan","Baku")
df_tyres['Grand_Prix'] = df_tyres['Grand_Prix'].str.replace("Spain","Barcelona")
df_tyres['Grand_Prix'] = df_tyres['Grand_Prix'].str.replace("Great Britain","Silverstone")
df_tyres['Grand_Prix'] = df_tyres['Grand_Prix'].str.replace("70TH Anniversary","Silverstone_70th")
df_tyres['Grand_Prix'] = df_tyres['Grand_Prix'].str.replace("Belgium","Spa-Francorchamps")
df_tyres['Grand_Prix'] = df_tyres['Grand_Prix'].str.replace("Italy","Monza")
df_tyres['Grand_Prix'] = df_tyres['Grand_Prix'].str.replace("Europe","Baku")
df_tyres['Grand_Prix'] = df_tyres['Grand_Prix'].str.replace("Russian","Russia")
df_tyres['Grand_Prix'] = df_tyres['Grand_Prix'].str.replace("Europa","Valencia")
df_tyres['Grand_Prix'] = df_tyres['Grand_Prix'].str.replace("Netherlands","Zandvoort")
df_tyres['Grand_Prix'] = df_tyres['Grand_Prix'].str.replace("Korea","South Korea")
df_tyres['Grand_Prix'] = df_tyres['Grand_Prix'].str.replace("Saudi Arabia","Jeddah")
df_tyres

       Year     Driver Grand_Prix       Tyres  Lap_changed
0      2012     Button  Australia   Soft Used           16
1      2012     Button  Australia  Medium New           36
2      2012     Button  Australia  Medium New           58
3      2012     Vettel  Australia   Soft Used           16
4      2012     Vettel  Australia   Soft Used           37
...     ...        ...        ...         ...          ...
11316  2013     Bottas     Brazil  Medium New           17
11317  2013     Bottas     Brazil    Hard New           41
11318  2013     Bottas     Brazil  Medium New           45
11319  2013   Grosjean     Brazil  Medium New            3
11320  2016  Gutierrez  Abu Dhabi    Soft New           28

[11321 rows x 5 columns]

In [1]:
import pandas as pd
import pymongo
import json
from datetime import datetime

In [36]:
client = pymongo.MongoClient()
database = client['projet']
collection = database['Race']

#race = df_race.to_json(orient="records")
#race = json.loads(race)
#collection.insert_many(race)

In [89]:
#cur = collection.find({"Grand_Prix":"Bahrain","Year":"2021"}).sort([("Points",-1)])
#list(cur)


# Best Speed average in the 2021 Bahrain Grand Prix


cur = collection.aggregate(
    [
        {"$match":{"Year":"2021","Grand_Prix":"Bahrain"}},
        {"$group": {"_id":"$Driver","Speed":{"$avg":"$Avg_Speed"}}},
        {"$sort":{"Speed":-1}},
        {"$limit":20}
    ]
)
list(cur)

[{'_id': 'Bottas', 'Speed': 211.566},
 {'_id': 'Verstappen', 'Speed': 208.984},
 {'_id': 'Perez', 'Speed': 207.33399999999997},
 {'_id': 'Hamilton', 'Speed': 207.235},
 {'_id': 'Gasly', 'Speed': 207.069},
 {'_id': 'Norris', 'Speed': 206.398},
 {'_id': 'Sainz', 'Speed': 206.151},
 {'_id': 'Tsunoda', 'Speed': 205.603},
 {'_id': 'Stroll', 'Speed': 205.378},
 {'_id': 'Ricciardo', 'Speed': 205.233},
 {'_id': 'Leclerc', 'Speed': 205.112},
 {'_id': 'Russell', 'Speed': 205.008},
 {'_id': 'Giovinazzi', 'Speed': 204.823},
 {'_id': 'RÃ¤ikkÃ¶nen', 'Speed': 204.672},
 {'_id': 'Ocon', 'Speed': 204.548},
 {'_id': 'Vettel', 'Speed': 203.871},
 {'_id': 'Alonso', 'Speed': 202.816},
 {'_id': 'Schumacher', 'Speed': 202.667},
 {'_id': 'Latifi', 'Speed': 201.685},
 {'_id': 'Mazepin', 'Speed': None}]

In [90]:
# Liste des constructeurs que le pilote a couru avec

cur = collection.aggregate(
    [
        {"$match":{"Driver":"Kvyat"}},
        {"$group": {"_id":"$Team"}},
        {"$limit":20}
    ]
)
list(cur)

[{'_id': 'Red Bull Racing Renault'},
 {'_id': 'AlphaTauri Honda'},
 {'_id': 'STR Renault'},
 {'_id': 'Red Bull Racing TAG Heuer'},
 {'_id': 'Toro Rosso'},
 {'_id': 'Toro Rosso Ferrari'},
 {'_id': 'Scuderia Toro Rosso Honda'}]

In [91]:
#Classement gÃ©nÃ©ral du pilote chaque annÃ©e

cur = collection.aggregate(
    [
        {"$match":{"Driver":"Vettel"}},
        {"$group": {"_id":"$Year","Position Averaged":{"$avg":"$Position"}}},
        {"$sort":{"Position Averaged":1}},
        #{"$limit":20}
    ]
)
list(cur)

[{'_id': '2013', 'Position Averaged': 1.8095238095238095},
 {'_id': '2017', 'Position Averaged': 2.6},
 {'_id': '2015', 'Position Averaged': 3.085714285714286},
 {'_id': '2018', 'Position Averaged': 3.2142857142857144},
 {'_id': '2016', 'Position Averaged': 4.1},
 {'_id': '2014', 'Position Averaged': 4.894736842105263},
 {'_id': '2012', 'Position Averaged': 5.0},
 {'_id': '2019', 'Position Averaged': 5.583333333333333},
 {'_id': '2020', 'Position Averaged': 10.32258064516129},
 {'_id': '2021', 'Position Averaged': 11.833333333333334}]

In [92]:
cur = collection.aggregate(
    [
        {"$match":{"Year":"2021"}},
        {"$group": {"_id":"$Team","Pitstop Time":{"$avg":"$Time_Pit"}}},
        {"$sort":{"Pitstop Time":1}},
        #{"$limit":20}
    ]
)
list(cur)

[{'_id': 'Red Bull Racing Honda', 'Pitstop Time': 24.10484375},
 {'_id': 'Mercedes', 'Pitstop Time': 24.233},
 {'_id': 'Ferrari', 'Pitstop Time': 24.54688235294118},
 {'_id': 'McLaren Mercedes', 'Pitstop Time': 24.875351851851853},
 {'_id': 'Williams Mercedes', 'Pitstop Time': 25.438727272727274},
 {'_id': 'Aston Martin Mercedes', 'Pitstop Time': 25.676309090909093},
 {'_id': 'Alfa Romeo Racing Ferrari', 'Pitstop Time': 25.732839285714284},
 {'_id': 'AlphaTauri Honda', 'Pitstop Time': 25.94745614035088},
 {'_id': 'Haas Ferrari', 'Pitstop Time': 26.281425925925923},
 {'_id': 'Alpine Renault', 'Pitstop Time': 26.49488679245283}]

In [93]:
cur = collection.aggregate(
    [
        {"$match":{"Driver":"Verstappen"}},
        {"$group": {"_id":"$Grand_Prix","Pitstop Time":{"$avg":"$Time_Pit"}}},
        {"$sort":{"Pitstop Time":1}},
        #{"$limit":20}
    ]
)
list(cur)

[{'_id': 'Jeddah', 'Pitstop Time': None},
 {'_id': 'Tuscany', 'Pitstop Time': None},
 {'_id': 'Zandvoort', 'Pitstop Time': 18.86},
 {'_id': 'Germany', 'Pitstop Time': 20.13692307692308},
 {'_id': 'Austria', 'Pitstop Time': 20.524875},
 {'_id': 'Baku', 'Pitstop Time': 20.6146},
 {'_id': 'Styria', 'Pitstop Time': 20.988},
 {'_id': 'Yas Island', 'Pitstop Time': 21.357599999999998},
 {'_id': 'Yas Marina', 'Pitstop Time': 21.778000000000002},
 {'_id': 'Barcelona', 'Pitstop Time': 22.141},
 {'_id': 'Brazil', 'Pitstop Time': 22.476},
 {'_id': 'Mexico', 'Pitstop Time': 22.572875},
 {'_id': 'China', 'Pitstop Time': 22.766846153846153},
 {'_id': 'Hungary', 'Pitstop Time': 22.810375},
 {'_id': 'Catalunya', 'Pitstop Time': 22.93},
 {'_id': 'Turkey', 'Pitstop Time': 23.00075},
 {'_id': 'Australia', 'Pitstop Time': 23.203166666666664},
 {'_id': 'Spa-Francorchamps', 'Pitstop Time': 23.70411111111111},
 {'_id': 'Japan', 'Pitstop Time': 24.80366666666667},
 {'_id': 'Portugal', 'Pitstop Time': 24.8556},
 {'_id': 'United States', 'Pitstop Time': 25.105909090909094},
 {'_id': 'Qatar', 'Pitstop Time': 25.313333333333333},
 {'_id': 'Malaysia', 'Pitstop Time': 25.665142857142857},
 {'_id': 'MontrÃ©al', 'Pitstop Time': 25.832599999999996},
 {'_id': 'Monza', 'Pitstop Time': 26.112545454545455},
 {'_id': 'Bahrain', 'Pitstop Time': 26.690857142857144},
 {'_id': 'Monaco', 'Pitstop Time': 28.54975},
 {'_id': 'France', 'Pitstop Time': 28.60975},
 {'_id': 'Silverstone', 'Pitstop Time': 28.7343},
 {'_id': 'Silverstone_70th', 'Pitstop Time': 29.0505},
 {'_id': 'Singapore', 'Pitstop Time': 29.116875},
 {'_id': 'Imola', 'Pitstop Time': 29.618000000000002},
 {'_id': 'Russia', 'Pitstop Time': 30.709555555555557}]

In [37]:
cur = collection.aggregate(
    [
        {"$match":{"Year":"2021",'Driver':"Verstappen"}},
        {"$project": {"_id":{"Grand Prix":"$Grand_Prix"},
                        "Time":{
                            "$dateFromString":{
                                "dateString":"$Q3",
                                "format":"%M:%S.%LZ",
                                "onError": '$Q3',
                                "onNull":"DNF"}
        }}},
        #{"$group": {"_id":"$Team"}},
        {"$sort":{"Time":1}},
        #{"$limit":20}
    ]
)
list(cur)

[{'_id': {'Grand Prix': 'Austria'}, 'Time': '01:03.720'},
 {'_id': {'Grand Prix': 'Styria'}, 'Time': '01:03.841'},
 {'_id': {'Grand Prix': 'Zandvoort'}, 'Time': '01:08.885'},
 {'_id': {'Grand Prix': 'Monaco'}, 'Time': '01:10.576'},
 {'_id': {'Grand Prix': 'Imola'}, 'Time': '01:14.498'},
 {'_id': {'Grand Prix': 'Hungary'}, 'Time': '01:15.840'},
 {'_id': {'Grand Prix': 'Mexico'}, 'Time': '01:16.225'},
 {'_id': {'Grand Prix': 'Barcelona'}, 'Time': '01:16.777'},
 {'_id': {'Grand Prix': 'Portugal'}, 'Time': '01:18.746'},
 {'_id': {'Grand Prix': 'Qatar'}, 'Time': '01:21.424'},
 {'_id': {'Grand Prix': 'Yas Island'}, 'Time': '01:22.109'},
 {'_id': {'Grand Prix': 'Turkey'}, 'Time': '01:23.196'},
 {'_id': {'Grand Prix': 'Jeddah'}, 'Time': '01:27.653'},
 {'_id': {'Grand Prix': 'Bahrain'}, 'Time': '01:28.997'},
 {'_id': {'Grand Prix': 'France'}, 'Time': '01:29.990'},
 {'_id': {'Grand Prix': 'United States'}, 'Time': '01:32.910'},
 {'_id': {'Grand Prix': 'Baku'}, 'Time': '01:41.563'},
 {'_id': {'Grand Prix': 'Russia'}, 'Time': '0NaN'}]

In [16]:
#Nombre de points du constructeur chaque annÃ©e

cur = collection.aggregate(
    [
        {"$match":{"Team":"Mercedes"}},
        {"$group": {"_id":"$Year","Total Points":{"$sum":"$Points"}}},
        {"$sort":{"Total Points":1}},
        #{"$limit":20}
    ]
)
list(cur)

[{'_id': '2012', 'Total Points': 142.0},
 {'_id': '2013', 'Total Points': 360.0},
 {'_id': '2021', 'Total Points': 502.0},
 {'_id': '2020', 'Total Points': 573.0},
 {'_id': '2018', 'Total Points': 655.0},
 {'_id': '2017', 'Total Points': 668.0},
 {'_id': '2014', 'Total Points': 701.0},
 {'_id': '2015', 'Total Points': 703.0},
 {'_id': '2019', 'Total Points': 739.0},
 {'_id': '2016', 'Total Points': 765.0}]

In [35]:
#Nombre de victoire du pilote chaque annÃ©e


cur = collection.aggregate(
    [
        {"$match":{"Driver":"Hamilton","Position":1}},
        {"$group": {"_id":"$Year","Number of wins":{"$sum":1}}},
        {"$sort":{"Number of wins":1}},
        #{"$limit":20}
    ]
)
list(cur)

[{'_id': '2013', 'Number of wins': 1},
 {'_id': '2012', 'Number of wins': 4},
 {'_id': '2021', 'Number of wins': 6},
 {'_id': '2017', 'Number of wins': 9},
 {'_id': '2016', 'Number of wins': 10},
 {'_id': '2015', 'Number of wins': 10},
 {'_id': '2019', 'Number of wins': 11},
 {'_id': '2014', 'Number of wins': 11},
 {'_id': '2018', 'Number of wins': 11},
 {'_id': '2020', 'Number of wins': 11}]

In [43]:
# Nombre d'abandon par annÃ©e
cur = collection.aggregate(
    [
        {"$match":{"Gap_Time":"DNF"}},
        {"$group": {"_id":"$Year","Number of DNF":{"$sum":1}}},
        {"$sort":{"Number of DNF":1}},
        #{"$limit":20}
    ]
)
list(cur)

[{'_id': '2021', 'Number of DNF': 34},
 {'_id': '2020', 'Number of DNF': 45},
 {'_id': '2019', 'Number of DNF': 54},
 {'_id': '2015', 'Number of DNF': 56},
 {'_id': '2013', 'Number of DNF': 58},
 {'_id': '2018', 'Number of DNF': 61},
 {'_id': '2016', 'Number of DNF': 63},
 {'_id': '2017', 'Number of DNF': 70},
 {'_id': '2014', 'Number of DNF': 71},
 {'_id': '2012', 'Number of DNF': 73}]

In [45]:
# Nombre d'abandon par annÃ©e sur un Grand Prix
cur = collection.aggregate(
    [
        {"$match":{"Gap_Time":"DNF","Grand_Prix":"Monaco"}},
        {"$group": {"_id":"$Year","Number of DNF":{"$sum":1}}},
        {"$sort":{"Number of DNF":1}},
        #{"$limit":20}
    ]
)
list(cur)

[{'_id': '2019', 'Number of DNF': 1},
 {'_id': '2021', 'Number of DNF': 1},
 {'_id': '2015', 'Number of DNF': 3},
 {'_id': '2018', 'Number of DNF': 3},
 {'_id': '2012', 'Number of DNF': 6},
 {'_id': '2014', 'Number of DNF': 6},
 {'_id': '2013', 'Number of DNF': 6},
 {'_id': '2017', 'Number of DNF': 7},
 {'_id': '2016', 'Number of DNF': 7}]

In [6]:
# Grand Prix avec le plus de DNF dans la decennie
cur = collection.aggregate(
    [
        {"$match":{"Gap_Time":"DNF"}},
        {"$group": {"_id":"$Grand_Prix","Number of DNF":{"$sum":1}}},
        {"$sort":{"Number of DNF":-1}},
        #{"$limit":20}
    ]
)
list(cur)

[{'_id': 'Monaco', 'Number of DNF': 40},
 {'_id': 'Australia', 'Number of DNF': 36},
 {'_id': 'Bahrain', 'Number of DNF': 31},
 {'_id': 'Singapore', 'Number of DNF': 30},
 {'_id': 'Austria', 'Number of DNF': 30},
 {'_id': 'Monza', 'Number of DNF': 27},
 {'_id': 'Hungary', 'Number of DNF': 27},
 {'_id': 'Silverstone', 'Number of DNF': 27},
 {'_id': 'United States', 'Number of DNF': 26},
 {'_id': 'Germany', 'Number of DNF': 25},
 {'_id': 'Malaysia', 'Number of DNF': 24},
 {'_id': 'Baku', 'Number of DNF': 23},
 {'_id': 'Spa-Francorchamps', 'Number of DNF': 22},
 {'_id': 'Brazil', 'Number of DNF': 20},
 {'_id': 'China', 'Number of DNF': 18},
 {'_id': 'Japan', 'Number of DNF': 17},
 {'_id': 'Barcelona', 'Number of DNF': 17},
 {'_id': 'Russia', 'Number of DNF': 16},
 {'_id': 'Canada', 'Number of DNF': 15},
 {'_id': 'Mexico', 'Number of DNF': 14},
 {'_id': 'Yas Marina', 'Number of DNF': 11},
 {'_id': 'MontrÃ©al', 'Number of DNF': 11},
 {'_id': 'Abu Dhabi', 'Number of DNF': 9},
 {'_id': 'Imola', 'Number of DNF': 8},
 {'_id': 'South Korea', 'Number of DNF': 7},
 {'_id': 'Yas Island', 'Number of DNF': 7},
 {'_id': 'Catalunya', 'Number of DNF': 7},
 {'_id': 'Tuscany', 'Number of DNF': 6},
 {'_id': 'India', 'Number of DNF': 6},
 {'_id': 'Valencia', 'Number of DNF': 5},
 {'_id': 'Jeddah', 'Number of DNF': 5},
 {'_id': 'Turkey', 'Number of DNF': 4},
 {'_id': 'France', 'Number of DNF': 4},
 {'_id': 'Zandvoort', 'Number of DNF': 3},
 {'_id': 'Styria', 'Number of DNF': 3},
 {'_id': 'Qatar', 'Number of DNF': 2},
 {'_id': 'Silverstone_70th', 'Number of DNF': 1},
 {'_id': 'Portugal', 'Number of DNF': 1}]

In [9]:
# Driver and Number of DNF in each Grand Prix
cur = collection.aggregate(
    [
        {"$match":{"Gap_Time":"DNF"}},
        {"$group": {"_id":{"Grand Prix":"$Grand_Prix","Driver":"$Driver"},"Number of DNF":{"$sum":1}}},
        {"$sort":{"Number of DNF":-1}},
        {"$limit":20}
    ]
)
list(cur)

[{'_id': {'Grand Prix': 'Australia', 'Driver': 'Grosjean'},
  'Number of DNF': 4},
 {'_id': {'Grand Prix': 'Australia', 'Driver': 'Ericsson'},
  'Number of DNF': 4},
 {'_id': {'Grand Prix': 'Monza', 'Driver': 'Alonso'}, 'Number of DNF': 4},
 {'_id': {'Grand Prix': 'Silverstone', 'Driver': 'Grosjean'},
  'Number of DNF': 4},
 {'_id': {'Grand Prix': 'Malaysia', 'Driver': 'Maldonado'},
  'Number of DNF': 4},
 {'_id': {'Grand Prix': 'Austria', 'Driver': 'Kvyat'}, 'Number of DNF': 3},
 {'_id': {'Grand Prix': 'Brazil', 'Driver': 'Grosjean'}, 'Number of DNF': 3},
 {'_id': {'Grand Prix': 'Baku', 'Driver': 'Kvyat'}, 'Number of DNF': 3},
 {'_id': {'Grand Prix': 'Australia', 'Driver': 'Maldonado'},
  'Number of DNF': 3},
 {'_id': {'Grand Prix': 'Russia', 'Driver': 'Ricciardo'}, 'Number of DNF': 3},
 {'_id': {'Grand Prix': 'Baku', 'Driver': 'Verstappen'}, 'Number of DNF': 3},
 {'_id': {'Grand Prix': 'China', 'Driver': 'Kvyat'}, 'Number of DNF': 3},
 {'_id': {'Grand Prix': 'Austria', 'Driver': 'Vettel'}, 'Number of DNF': 3},
 {'_id': {'Grand Prix': 'Singapore', 'Driver': 'Button'}, 'Number of DNF': 3},
 {'_id': {'Grand Prix': 'Hungary', 'Driver': 'Grosjean'}, 'Number of DNF': 3},
 {'_id': {'Grand Prix': 'MontrÃ©al', 'Driver': 'Alonso'}, 'Number of DNF': 3},
 {'_id': {'Grand Prix': 'Australia', 'Driver': 'Ricciardo'},
  'Number of DNF': 3},
 {'_id': {'Grand Prix': 'Monaco', 'Driver': 'Kvyat'}, 'Number of DNF': 3},
 {'_id': {'Grand Prix': 'Hungary', 'Driver': 'Hulkenberg'},
  'Number of DNF': 3},
 {'_id': {'Grand Prix': 'United States', 'Driver': 'Hulkenberg'},
  'Number of DNF': 3}]

In [11]:
# Driver with most pole position in the decade
cur = collection.aggregate(
    [
        {"$match":{"Pos_Qualif":"1"}},
        {"$group": {"_id":"$Driver","Number of Pole Position":{"$sum":1}}},
        {"$sort":{"Number of Pole Position":-1}},
        {"$limit":20}
    ]
)
list(cur)

[{'_id': 'Hamilton', 'Number of Pole Position': 85},
 {'_id': 'Rosberg', 'Number of Pole Position': 30},
 {'_id': 'Vettel', 'Number of Pole Position': 27},
 {'_id': 'Bottas', 'Number of Pole Position': 18},
 {'_id': 'Verstappen', 'Number of Pole Position': 11},
 {'_id': 'Leclerc', 'Number of Pole Position': 8},
 {'_id': 'Ricciardo', 'Number of Pole Position': 3},
 {'_id': 'Webber', 'Number of Pole Position': 3},
 {'_id': 'Alonso', 'Number of Pole Position': 2},
 {'_id': 'RÃ¤ikkÃ¶nen', 'Number of Pole Position': 2},
 {'_id': 'Massa', 'Number of Pole Position': 1},
 {'_id': 'Stroll', 'Number of Pole Position': 1},
 {'_id': 'Norris', 'Number of Pole Position': 1},
 {'_id': 'Button', 'Number of Pole Position': 1},
 {'_id': 'Schumacher', 'Number of Pole Position': 1},
 {'_id': 'Maldonado', 'Number of Pole Position': 1}]

In [13]:
# Driver with most win in the decade
cur = collection.aggregate(
    [
        {"$match":{"Position":1}},
        {"$group": {"_id":"$Driver","Number of Wins":{"$sum":1}}},
        {"$sort":{"Number of Wins":-1}},
        {"$limit":20}
    ]
)
list(cur)

[{'_id': 'Hamilton', 'Number of Wins': 84},
 {'_id': 'Vettel', 'Number of Wins': 32},
 {'_id': 'Rosberg', 'Number of Wins': 23},
 {'_id': 'Verstappen', 'Number of Wins': 19},
 {'_id': 'Bottas', 'Number of Wins': 10},
 {'_id': 'Ricciardo', 'Number of Wins': 7},
 {'_id': 'Alonso', 'Number of Wins': 5},
 {'_id': 'RÃ¤ikkÃ¶nen', 'Number of Wins': 3},
 {'_id': 'Button', 'Number of Wins': 3},
 {'_id': 'Leclerc', 'Number of Wins': 2},
 {'_id': 'Perez', 'Number of Wins': 2},
 {'_id': 'Webber', 'Number of Wins': 2},
 {'_id': 'Gasly', 'Number of Wins': 1},
 {'_id': 'Ocon', 'Number of Wins': 1},
 {'_id': 'Maldonado', 'Number of Wins': 1}]

In [3]:
# Averaged Max Speed for each Grand Prix

cur = collection.aggregate(
    [
        {"$group": {"_id":"$Grand_Prix","Speed Averaged":{"$avg":"$Avg_Speed"}}},
        {"$sort":{"Speed Averaged":-1}},
        #{"$limit":20}
    ]
)
list(cur)

[{'_id': 'Monza', 'Speed Averaged': 240.65527567567568},
 {'_id': 'Jeddah', 'Speed Averaged': 239.25889999999998},
 {'_id': 'Silverstone_70th', 'Speed Averaged': 234.24825},
 {'_id': 'Styria', 'Speed Averaged': 225.2390263157895},
 {'_id': 'Spa-Francorchamps', 'Speed Averaged': 225.16821511627904},
 {'_id': 'Imola', 'Speed Averaged': 224.23407692307694},
 {'_id': 'Qatar', 'Speed Averaged': 223.5314},
 {'_id': 'Silverstone', 'Speed Averaged': 222.74085227272727},
 {'_id': 'Austria', 'Speed Averaged': 222.0509430379747},
 {'_id': 'France', 'Speed Averaged': 218.62041379310347},
 {'_id': 'Japan', 'Speed Averaged': 212.68452439024392},
 {'_id': 'Australia', 'Speed Averaged': 210.6785806451613},
 {'_id': 'Russia', 'Speed Averaged': 210.35848344370862},
 {'_id': 'Tuscany', 'Speed Averaged': 208.05327777777777},
 {'_id': 'Portugal', 'Speed Averaged': 206.2433076923077},
 {'_id': 'India', 'Speed Averaged': 206.06024444444444},
 {'_id': 'Zandvoort', 'Speed Averaged': 205.48555000000002},
 {'_id': 'MontrÃ©al', 'Speed Averaged': 204.82945263157893},
 {'_id': 'Germany', 'Speed Averaged': 203.86920945945946},
 {'_id': 'Bahrain', 'Speed Averaged': 203.26092694063928},
 {'_id': 'Brazil', 'Speed Averaged': 202.89035443037974},
 {'_id': 'Baku', 'Speed Averaged': 202.69325252525255},
 {'_id': 'Yas Island', 'Speed Averaged': 202.32601694915255},
 {'_id': 'Canada', 'Speed Averaged': 199.47344615384614},
 {'_id': 'Turkey', 'Speed Averaged': 198.9053},
 {'_id': 'Barcelona', 'Speed Averaged': 197.49140277777778},
 {'_id': 'Malaysia', 'Speed Averaged': 195.737312},
 {'_id': 'China', 'Speed Averaged': 195.36934730538923},
 {'_id': 'United States', 'Speed Averaged': 195.07770391061453},
 {'_id': 'South Korea', 'Speed Averaged': 195.04927272727272},
 {'_id': 'Yas Marina', 'Speed Averaged': 191.28267499999998},
 {'_id': 'Mexico', 'Speed Averaged': 190.1162608695652},
 {'_id': 'Catalunya', 'Speed Averaged': 188.5580172413793},
 {'_id': 'Abu Dhabi', 'Speed Averaged': 188.1805},
 {'_id': 'Hungary', 'Speed Averaged': 186.9327014925373},
 {'_id': 'Valencia', 'Speed Averaged': 186.93056521739132},
 {'_id': 'Singapore', 'Speed Averaged': 165.522263803681},
 {'_id': 'Monaco', 'Speed Averaged': 152.72267955801104}]

In [5]:
# Rank of fastest pilots in a team during the decade

cur = collection.aggregate(
    [
        {"$match":{"Team":"McLaren Mercedes"}},
        {"$group": {"_id":"$Driver","Speed Averaged":{"$avg":"$Avg_Speed"}}},
        {"$sort":{"Speed Averaged":-1}},
        #{"$limit":20}
    ]
)
list(cur)
#McLaren Mercedes

[{'_id': 'Norris', 'Speed Averaged': 210.9654705882353},
 {'_id': 'Ricciardo', 'Speed Averaged': 208.11555555555555},
 {'_id': 'Perez', 'Speed Averaged': 199.099},
 {'_id': 'Button', 'Speed Averaged': 197.9502105263158},
 {'_id': 'Hamilton', 'Speed Averaged': 197.00215789473685},
 {'_id': 'Magnussen', 'Speed Averaged': 195.66926315789473}]

In [18]:
df_tyres

       Year     Driver Grand_Prix       Tyres  Lap_changed
0      2012     Button  Australia   Soft Used           16
1      2012     Button  Australia  Medium New           36
2      2012     Button  Australia  Medium New           58
3      2012     Vettel  Australia   Soft Used           16
4      2012     Vettel  Australia   Soft Used           37
...     ...        ...        ...         ...          ...
11316  2013     Bottas     Brazil  Medium New           17
11317  2013     Bottas     Brazil    Hard New           41
11318  2013     Bottas     Brazil  Medium New           45
11319  2013   Grosjean     Brazil  Medium New            3
11320  2016  Gutierrez  Abu Dhabi    Soft New           28

[11321 rows x 5 columns]

In [14]:
client = pymongo.MongoClient()
database = client['projet']
collection_t = database['Tyres']

#tyres = df_tyres.to_json(orient="records")
#tyres = json.loads(tyres)
#collection_t.insert_many(tyres)

In [23]:
# Type of tyres used in Grand Prix
cur = collection_t.aggregate(
    [
        {"$match":{"Grand_Prix":"Russia"}},
        {"$group": {"_id":{"Year":"$Year","Tyres":"$Tyres"},"Number of tyres used":{"$sum":1}}},
        {"$sort":{"Number of tyres used":-1}},
        #{"$limit":20}
    ]
)
list(cur)

[{'_id': {'Year': '2014', 'Tyres': 'Medium New'}, 'Number of tyres used': 21},
 {'_id': {'Year': '2021', 'Tyres': 'Medium New'}, 'Number of tyres used': 20},
 {'_id': {'Year': '2018', 'Tyres': 'Soft New'}, 'Number of tyres used': 20},
 {'_id': {'Year': '2021', 'Tyres': 'Hard New'}, 'Number of tyres used': 20},
 {'_id': {'Year': '2015', 'Tyres': 'Soft New'}, 'Number of tyres used': 18},
 {'_id': {'Year': '2020', 'Tyres': 'Hard New'}, 'Number of tyres used': 18},
 {'_id': {'Year': '2019', 'Tyres': 'Medium New'}, 'Number of tyres used': 17},
 {'_id': {'Year': '2016', 'Tyres': 'Soft New'}, 'Number of tyres used': 17},
 {'_id': {'Year': '2017', 'Tyres': 'Supersoft New'},
  'Number of tyres used': 16},
 {'_id': {'Year': '2020', 'Tyres': 'Medium New'}, 'Number of tyres used': 15},
 {'_id': {'Year': '2021', 'Tyres': 'Intermediate New'},
  'Number of tyres used': 14},
 {'_id': {'Year': '2014', 'Tyres': 'Soft New'}, 'Number of tyres used': 13},
 {'_id': {'Year': '2016', 'Tyres': 'Supersoft Used'},
  'Number of tyres used': 12},
 {'_id': {'Year': '2017', 'Tyres': 'Ultrasoft New'},
  'Number of tyres used': 12},
 {'_id': {'Year': '2019', 'Tyres': 'Soft Used'}, 'Number of tyres used': 12},
 {'_id': {'Year': '2017', 'Tyres': 'Ultrasoft Used'},
  'Number of tyres used': 11},
 {'_id': {'Year': '2016', 'Tyres': 'Supersoft New'},
  'Number of tyres used': 11},
 {'_id': {'Year': '2015', 'Tyres': 'Supersoft Used'},
  'Number of tyres used': 11},
 {'_id': {'Year': '2019', 'Tyres': 'Soft New'}, 'Number of tyres used': 10},
 {'_id': {'Year': '2015', 'Tyres': 'Supersoft New'},
  'Number of tyres used': 10},
 {'_id': {'Year': '2014', 'Tyres': 'Soft Used'}, 'Number of tyres used': 10},
 {'_id': {'Year': '2018', 'Tyres': 'Ultrasoft New'},
  'Number of tyres used': 9},
 {'_id': {'Year': '2020', 'Tyres': 'Soft Used'}, 'Number of tyres used': 8},
 {'_id': {'Year': '2018', 'Tyres': 'Hiper Blando Usado'},
  'Number of tyres used': 6},
 {'_id': {'Year': '2021', 'Tyres': 'Intermediate Used'},
  'Number of tyres used': 4},
 {'_id': {'Year': '2018', 'Tyres': 'Ultrasoft Used'},
  'Number of tyres used': 4},
 {'_id': {'Year': '2016', 'Tyres': 'Soft Used'}, 'Number of tyres used': 3},
 {'_id': {'Year': '2019', 'Tyres': 'Hard New'}, 'Number of tyres used': 3},
 {'_id': {'Year': '2020', 'Tyres': 'Medium Used'}, 'Number of tyres used': 2},
 {'_id': {'Year': '2016', 'Tyres': 'Medium New'}, 'Number of tyres used': 2},
 {'_id': {'Year': '2019', 'Tyres': 'Medium Used'}, 'Number of tyres used': 2},
 {'_id': {'Year': '2018', 'Tyres': 'Hiper Blando Nuevo'},
  'Number of tyres used': 1},
 {'_id': {'Year': '2021', 'Tyres': 'Soft New'}, 'Number of tyres used': 1},
 {'_id': {'Year': '2016', 'Tyres': 'Medium Used'}, 'Number of tyres used': 1},
 {'_id': {'Year': '2020', 'Tyres': 'Soft New'}, 'Number of tyres used': 1}]

In [47]:
client = pymongo.MongoClient()
database = client['projet']
collection_p = database['Pitstop']

pitstop = df_pitstop.to_json(orient="records")
pitstop = json.loads(pitstop)
collection_p.insert_many(pitstop)

In [59]:
cur = collection_p.aggregate(
    [
        {"$match":{"Year":"2021","Grand_Prix":"Russia",}},
        #{"$group": {"_id":{"Team":"$Team"},"Best Time at the pitlane":{"$avg":"$Time_Pit"}}},
        {"$project": {"_id":{"Team":"$Team","Stop Number :":"$Num_stop"},
                        "Best Time at the pitlane":{
                            "$dateFromString":{
                                "dateString":"$Time_Pit",
                                "format":"%S.%LZ",
                                "onError": '$Time_Pit',
                                "onNull":"DNF"}
        }}},
        {"$sort":{"Best Time at the pitlane":1}},
        #{"$limit":20}
    ]
)
list(cur)

[{'_id': {'Team': 'Aston Martin Mercedes', 'Stop Number :': 1.0},
  'Best Time at the pitlane': '29.242'},
 {'_id': {'Team': 'AlphaTauri Honda', 'Stop Number :': 1.0},
  'Best Time at the pitlane': '29.354'},
 {'_id': {'Team': 'Mercedes', 'Stop Number :': 2.0},
  'Best Time at the pitlane': '29.569'},
 {'_id': {'Team': 'Red Bull Racing Honda', 'Stop Number :': 1.0},
  'Best Time at the pitlane': '29.578'},
 {'_id': {'Team': 'McLaren Mercedes', 'Stop Number :': 1.0},
  'Best Time at the pitlane': '29.824'},
 {'_id': {'Team': 'Mercedes', 'Stop Number :': 1.0},
  'Best Time at the pitlane': '29.878'},
 {'_id': {'Team': 'Alpine Renault', 'Stop Number :': 1.0},
  'Best Time at the pitlane': '29.901'},
 {'_id': {'Team': 'Mercedes', 'Stop Number :': 1.0},
  'Best Time at the pitlane': '29.936'},
 {'_id': {'Team': 'Haas Ferrari', 'Stop Number :': 1.0},
  'Best Time at the pitlane': '29.996'},
 {'_id': {'Team': 'Mercedes', 'Stop Number :': 2.0},
  'Best Time at the pitlane': '30.045'},
 {'_id': {'Team': 'Williams Mercedes', 'Stop Number :': 1.0},
  'Best Time at the pitlane': '30.056'},
 {'_id': {'Team': 'Alfa Romeo Racing Ferrari', 'Stop Number :': 1.0},
  'Best Time at the pitlane': '30.081'},
 {'_id': {'Team': 'Alfa Romeo Racing Ferrari', 'Stop Number :': 1.0},
  'Best Time at the pitlane': '30.102'},
 {'_id': {'Team': 'AlphaTauri Honda', 'Stop Number :': 1.0},
  'Best Time at the pitlane': '30.112'},
 {'_id': {'Team': 'Haas Ferrari', 'Stop Number :': 1.0},
  'Best Time at the pitlane': '30.127'},
 {'_id': {'Team': 'Alfa Romeo Racing Ferrari', 'Stop Number :': 2.0},
  'Best Time at the pitlane': '30.131'},
 {'_id': {'Team': 'Alpine Renault', 'Stop Number :': 1.0},
  'Best Time at the pitlane': '30.157'},
 {'_id': {'Team': 'Aston Martin Mercedes', 'Stop Number :': 1.0},
  'Best Time at the pitlane': '30.241'},
 {'_id': {'Team': 'Williams Mercedes', 'Stop Number :': 1.0},
  'Best Time at the pitlane': '30.665'},
 {'_id': {'Team': 'Ferrari', 'Stop Number :': 2.0},
  'Best Time at the pitlane': '30.677'},
 {'_id': {'Team': 'Alpine Renault', 'Stop Number :': 2.0},
  'Best Time at the pitlane': '30.702'},
 {'_id': {'Team': 'Ferrari', 'Stop Number :': 1.0},
  'Best Time at the pitlane': '30.715'},
 {'_id': {'Team': 'AlphaTauri Honda', 'Stop Number :': 3.0},
  'Best Time at the pitlane': '30.972'},
 {'_id': {'Team': 'AlphaTauri Honda', 'Stop Number :': 2.0},
  'Best Time at the pitlane': '30.980'},
 {'_id': {'Team': 'McLaren Mercedes', 'Stop Number :': 2.0},
  'Best Time at the pitlane': '31.016'},
 {'_id': {'Team': 'Red Bull Racing Honda', 'Stop Number :': 2.0},
  'Best Time at the pitlane': '31.017'},
 {'_id': {'Team': 'Ferrari', 'Stop Number :': 1.0},
  'Best Time at the pitlane': '31.849'},
 {'_id': {'Team': 'AlphaTauri Honda', 'Stop Number :': 2.0},
  'Best Time at the pitlane': '31.915'},
 {'_id': {'Team': 'Williams Mercedes', 'Stop Number :': 2.0},
  'Best Time at the pitlane': '32.081'},
 {'_id': {'Team': 'Aston Martin Mercedes', 'Stop Number :': 2.0},
  'Best Time at the pitlane': '32.128'},
 {'_id': {'Team': 'Red Bull Racing Honda', 'Stop Number :': 2.0},
  'Best Time at the pitlane': '32.313'},
 {'_id': {'Team': 'Ferrari', 'Stop Number :': 2.0},
  'Best Time at the pitlane': '32.648'},
 {'_id': {'Team': 'McLaren Mercedes', 'Stop Number :': 2.0},
  'Best Time at the pitlane': '32.670'},
 {'_id': {'Team': 'Alpine Renault', 'Stop Number :': 2.0},
  'Best Time at the pitlane': '33.264'},
 {'_id': {'Team': 'McLaren Mercedes', 'Stop Number :': 1.0},
  'Best Time at the pitlane': '33.617'},
 {'_id': {'Team': 'Haas Ferrari', 'Stop Number :': 2.0},
  'Best Time at the pitlane': '33.931'},
 {'_id': {'Team': 'Alfa Romeo Racing Ferrari', 'Stop Number :': 2.0},
  'Best Time at the pitlane': '33.961'},
 {'_id': {'Team': 'Red Bull Racing Honda', 'Stop Number :': 1.0},
  'Best Time at the pitlane': '36.026'},
 {'_id': {'Team': 'Aston Martin Mercedes', 'Stop Number :': 2.0},
  'Best Time at the pitlane': '43.124'}]